feat: add generate-ssh-key command and fix init script

diff --git a/scripts/alias_json b/scripts/alias_json
--- a/scripts/alias_json
+++ b/scripts/alias_json
@@ -1,10 +1,12 @@
 #!/bin/bash
 
-[ ! "$_INIT_COMPLETE" ] && source $HOME/github/shell-settings/scripts/.INIT && export _INIT_COMPLETE=1
+[ -z $SHELL_SETTINGS_DIR ] && source $HOME/github/shell-settings/scripts/.INIT
 
-if ! command -v gron &> /dev/null; then
-  log "command 'json' not found, installing gron now..."
-  i gron
+cmd="gron"
+
+if ! command -v "${cmd}" &> /dev/null; then
+  log "command '${cmd}' not found, installing ${cmd} now..."
+  i "${cmd}"
 fi
 
-gron "$@"
+"${cmd}" "$@"
diff --git a/scripts/alias_nnn b/scripts/alias_nnn
--- a/scripts/alias_nnn
+++ b/scripts/alias_nnn
@@ -1,9 +1,12 @@
 #!/bin/bash
 
-[ ! "$_INIT_COMPLETE" ] && source $HOME/github/shell-settings/scripts/.INIT && export _INIT_COMPLETE=1
+[ -z $SHELL_SETTINGS_DIR ] && source $HOME/github/shell-settings/scripts/.INIT
 
-if ! command -v nnn &> /dev/null; then
-  i nnn
+cmd="nnn"
+
+if ! command -v "${cmd}" &> /dev/null; then
+  log "command '${cmd}' not found, installing ${cmd} now..."
+  i "${cmd}"
 fi
 
-nnn "$@"
+"${cmd}" "$@"
