fixes and non-fixes garbage in garbage for sure out

diff --git a/scripts/pkgm b/scripts/pkgm
--- a/scripts/pkgm
+++ b/scripts/pkgm
@@ -1,7 +1,19 @@
 #!/bin/bash
 
-if ! command -v pkgm; then
-  brew install pkgxdev/made/pkgm || curl https://pkgx.sh | sh
-else
-  pkgm "$@"
-fi
+[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/_INIT
+
+main() {
+  if ! non_local_bin_path pkgm; then
+    log "pkgm installation missing, running installer..."
+    brew install pkgxdev/made/pkgm || curl https://pkgx.sh | sh
+  fi
+
+  if non_local_bin_path pkgm; then
+    export PATH=$NON_LOCAL_BIN_PATH
+    pkgm "$@"
+  else
+    die "Unable to install or locate pkgm"
+  fi
+}
+
+main "$@"
diff --git a/scripts/pkgo b/scripts/pkgo
--- a/scripts/pkgo
+++ b/scripts/pkgo
@@ -3,13 +3,16 @@
 [ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/_INIT
 
 main() {
-  if ! exists pkgo; then
+  if ! non_local_bin_path pkgo; then
     log "pkgo installation missing, running installer..."
-    curl -O https://raw.githubusercontent.com/pkgxdev/pkgo/refs/heads/main/entrypoint.ts
-    sudo install -m 755 entrypoint.ts /usr/local/bin/pkgo}
+    sudo pkgm install pkgo
+  fi
+
+  if non_local_bin_path pkgo; then
+    export PATH=$NON_LOCAL_BIN_PATH
+    pkgo "$@"
   else
-    echo "fail"
-    #command pkgo "$@"
+    die "Unable to install or locate pkgo"
   fi
 }
 
